#!/bin/bash
sdcard=
image_name=$BOARD-$OPI_SYSTEM_TYPE-$OPI_SYSTEM_VERSION

create=1

HOSTNAME="orangepi"
rootfs=$OPI_SYSTEM_OUTPUT_DIR
if [ "$(id -u)" != "0" ]; then
   echo "Script must be run as root !"
   exit 0
fi

message "check installed software ....."
	apt-get install -y -q partd 
if [  "$(fdisk -l $sdcard)" == "" ]
then
	echo "sdcard dev not found!!!"
	exit 0
fi
boot_size=${OPI_SDCARD_BOOT_SIZE}
boot_start=${OPI_SDCARD_BOOT_START}
sdcard_sectors=`fdisk -l $sdcard | grep "Disk $sdcard" | awk '{print $7}'`
sdcard_bytes=`fdisk -l $sdcard | grep "Disk $sdcard" | awk '{print $5}'`
sdcard_block=$(expr $sdcard_bytes / $sdcard_sectors )
block_size=$(expr 1024 \* 1024 / $sdcard_block )
sdcard_size=$(expr $sdcard_bytes / 1024 / 1024 )
root_size=$(expr  $sdcard_size - $boot_size - $(expr $boot_start / $block_size ) )
boot_end=$(expr $boot_start + $(expr $boot_size \* $block_size ) - 1)
root_start=$(expr $boot_end + 1)
root_end=$(expr $(expr $root_size \* $block_size ) + $root_start - 1 )


echo ""
echo " sdcard dev :   $sdcard"
echo " sdcard total size   :  $sdcard_size	M"
echo " boot partition size :  $boot_size	M"
echo " root partition size :  $root_size	M"
echo " boot start : $boot_start"
echo " boot end   : $boot_end"
echo " root start : $root_start"
echo " root end   : $root_end"
echo ""


# Create the disk and partition it
# We start out at around 3MB so there is room to write u-boot without issues.
echo "Creating image file for NanoPi2"
dd if=/dev/zero of=${basedir}/kali-$1-nanopi2.img bs=1M count=7000
parted kali-$1-nanopi2.img --script -- mklabel msdos
parted kali-$1-nanopi2.img --script -- mkpart primary ext4 3072s 264191s
parted kali-$1-nanopi2.img --script -- mkpart primary ext4 264192s 100%

# Set the partition variables
loopdevice=`losetup -f --show ${basedir}/kali-$1-nanopi2.img`
device=`kpartx -va $loopdevice| sed -E 's/.*(loop[0-9])p.*/\1/g' | head -1`
sleep 5
device="/dev/mapper/${device}"
bootp=${device}p1
rootp=${device}p2

# Create file systems
mkfs.ext4 $bootp
mkfs.ext4 $rootp

# Create the dirs for the partitions and mount them
mkdir -p ${basedir}/bootp ${basedir}/root
mount $bootp ${basedir}/bootp
mount $rootp ${basedir}/root

echo "Rsyncing rootfs into image file"
rsync -HPavz -q ${basedir}/kali-$architecture/ ${basedir}/root/

# Serial console settings.
# (No auto login)
echo 'T1:12345:respawn:/sbin/agetty 115200 ttyAMA0 vt100' >> ${basedir}/root/etc/inittab

cd ${basedir}

cp ${basedir}/../misc/zram ${basedir}/root/etc/init.d/zram
chmod +x ${basedir}/root/etc/init.d/zram

# Unmount partitions
umount $bootp
umount $rootp
kpartx -dv $loopdevice

# Samsung bootloaders must be signed.
# These are the same steps that are done by
# https://github.com/friendlyarm/sd-fuse_nanopi2/blob/master/fusing.sh
dd if=${basedir}/../misc/nanopi2/2ndboot.bin of=$loopdevice bs=512 seek=1
dd if=${basedir}/../misc/nanopi2/boot.TBI of=$loopdevice bs=512 seek=64 count=1
dd if=${basedir}/../misc/nanopi2/bootloader of=$loopdevice bs=512 seek=65
sync

cd ${basedir}

losetup -d $loopdevice

# Clean up all the temporary build stuff and remove the directories.
# Comment this out to keep things around if you want to see what may have gone
# wrong.
echo "Clean up the build system"
rm -rf ${basedir}/bootp ${basedir}/root ${basedir}/kali-$architecture ${basedir}/patches

# If you're building an image for yourself, comment all of this out, as you
# don't need the sha1sum or to compress the image, since you will be testing it
# soon.
echo "Generating sha1sum for kali-$1-nanopi2.img"
sha1sum kali-$1-nanopi2.img > ${basedir}/kali-$1-nanopi2.img.sha1sum











read -p "Will clear the SD card data, whether or not to continue ?[y/n]"  continue
if [ "$continue" == "y" ];then
	mount_dev=`mount | grep $sdcard | awk '{print $3}'`
	umount -f $mount_dev
	echo ""
	echo -e "d\n\nd\n\nd\n\nd\n\nw\n" | fdisk $sdcard > /dev/null 
	#echo " dd sdcard........"
	#dd if=/dev/zero of=$sdcard  count=1

	echo "fdisk sdcard..........."
	echo -e "n\np\n1\n${boot_start}\n${boot_end}\nt\nb\nw\n" | fdisk $sdcard 
	echo -e "n\np\n2\n${root_start}\n${root_end}\nw\n" | fdisk $sdcard  
	fdisk -l $sdcard
	echo ""

	check_boot=`fdisk -l $sdcard | grep $sdcard"1" | awk '{print $2}'`
	check_root=`fdisk -l $sdcard | grep $sdcard"2" | awk '{print $2}'`

	if [[ $check_boot == $boot_start  && $check_root == $root_start ]];then
		echo "mkfs image............"
		sleep 3
		mkfs.vfat $sdcard"1"
		sleep 3
		dosfslabel $sdcard"1" "BOOT"
		sleep 3
		mkfs.ext4 $sdcard"2"
		sleep 3
		e2label $sdcard"2" "ROOTFS"
		echo ""
	fi
else 
	echo "exit"
	exit 0
fi


#mount partition
sleep 1
mkdir -p $OPI_SDCARD_BOOT $OPI_SDCARD_ROOT
echo "mount -t vfat $sdcard"1" $OPI_SDCARD_BOOT"
mount -t vfat $sdcard"1" $OPI_SDCARD_BOOT
sleep 1
echo "mount -t ext4 $sdcard"2" $OPI_SDCARD_ROOT"
mount -t ext4 $sdcard"2" $OPI_SDCARD_ROOT

#read -p "Enter any key, close to mount :"
#fuser -ck $OPI_SDCARD_BOOT
#fuser -ck $OPI_SDCARD_ROOT
#umount -f $OPI_SDCARD_BOOT
#umount -f $OPI_SDCARD_ROOT
#echo "umount :$OPI_SDCARD_BOOT"
#echo "umount :$OPI_SDCARD_ROOT"

echo ""
echo "^_^"
